######################################################################
# Automatically generated by qmake (2.00a) ??? ?? 17 15:55:01 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ImageViewer.h
FORMS += ImageViewer.ui
SOURCES += ImageViewer.cpp main.cpp
RESOURCES += Histopatho-GTMRes.qrc
